from Kurama import (SAGE, SHINOBI, DEMONS, TIGERS, BEASTS, telethn)

IMMUNE_USERS = SHINOBI + BEASTS + DEMONS + TIGERS + SAGE

IMMUNE_USERS = list(SHINOBI) + list(BEASTS) + list(DEMONS) + list(
    TIGERS) + list(SAGE)
